# Generated by Django 3.2.9 on 2021-12-14 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(default='test', max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default='do somthing', max_length=10000)),
                ('priority', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], default=3, max_length=7)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Working', 'Working'), ('Done', 'Done')], default=1, max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('category', models.ManyToManyField(to='app.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
